title: Project

status:
  draft: Draft
  listed: Published

columns:
  left:
    width: 1/3
    fields:
      cover:
        type: files
        label: Cover
        layout: cards
        info: "{{ file.dimensions }}"
        template: cover
        min: 1
        max: 1
      accent:
        type: colors
        label: Accent Color
        contrast:
            - '#F0ECE9'
      category:
        type: tags
        label: Category
        options:
          - Interior Design
          - Editorial Writing
          - Production
          - Art Direction

      client:
        type: text
  
  right:
    width: 2/3
    fields:
      intro:
        type: writer
        label: Introduction

      casestudy:
        type: layout
        label: Case Study
        layouts:
          - "1/1"
          - "1/2, 1/2"
          - "1/3, 1/3, 1/3"