title: Project

status:
  draft: Draft
  listed: Published

columns:
  left:
    width: 1/3
    fields:
      cover:
        type: files
        label: Cover
        info: "{{ file.dimensions }}"
        template: cover
        min: 1
        max: 3
      accent:
        type: colors
        label: Accent Color
        contrast:
            - '#F0ECE9'
      category:
        type: select
        label: Category
        options:
          interior-design: Interior Design
          editorial-writing: Editorial Writing
          art-direction: Art Direction
      client:
        label: Client
        type: text
      link:
        label: Project Link
        type: url
      credits:
        label: Project Credits
        type: structure
        fields:
          role:
            label: Role
            type: text
          name:
            label: Name
            type: text

  right:
    width: 2/3
    fields:
      vanitytitle:
        type: text
        label: Vanity Title
        help: This is we can use to create a more beautiful title section. You can use `</br>` to create line breaks. If left empty. The page title above will be used.
      intro:
        type: writer
        label: Introduction
      casestudy:
        type: layout
        label: Case Study
        layouts:
          - "1/1"
          - "1/2, 1/2"
          - "1/3, 1/3, 1/3"
        settings:
          fields:
            class:
              type: text
              width: 1/2
            id:
              type: text
              width: 1/2