title: Site
preset: page
fields:
  headline:
    label: Headline
    type: text
  text:
    label: Text
    type: textarea
  features:
    label: Features
    type: structure
    fields:
      name:
        label: Publication
        type: text