# This is a basic workflow to help you get started with Actions

name: Deploy to dev server
on:
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.3.2
      with:
        server: ftp.akuko.studio
        username: akuko
        password: ${{ secrets.FTPS_PASSWORD }}
        local-dir: ./www/
        server-dir: ./home/akuko/akuko/judithaw/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/content/**
